import type { Arrangement, Category } from "./types";

// Estos datos de ejemplo se muestran cuando Sanity todavía NO está
// configurado, para que veas el sitio funcionando de inmediato.
// Cuando conectes tu proyecto de Sanity, se usan tus datos reales.

export const sampleCategories: Category[] = [
  { _id: "c1", name: "Ramos", slug: "ramos", order: 1 },
  { _id: "c2", name: "Cajas", slug: "cajas", order: 2 },
  { _id: "c3", name: "Eventos", slug: "eventos", order: 3 },
  { _id: "c4", name: "Plantas", slug: "plantas", order: 4 },
];

export const sampleArrangements: Arrangement[] = [
  {
    _id: "a1",
    name: "Tierra Cálida",
    slug: "tierra-calida",
    price: 265,
    category: { name: "Ramos", slug: "ramos" },
    shortDescription:
      "Tonos terracota y ocre que evocan la calidez de la tierra. Arreglo de temporada con carácter.",
    flowers: ["protea", "paja de trigo", "craspedia", "eucalipto semilla"],
    isFeatured: true,
    isAvailable: true,
    order: 1,
  },
  {
    _id: "a2",
    name: "Verde Raíz",
    slug: "verde-raiz",
    price: 290,
    category: { name: "Ramos", slug: "ramos" },
    shortDescription:
      "Follajes y flores verdes en un ramo que se siente vivo. Minimalista y con mucha textura.",
    flowers: ["helecho", "anthurium verde", "eucalipto", "amaranthus"],
    isFeatured: true,
    isAvailable: true,
    order: 2,
  },
  {
    _id: "a3",
    name: "Blanco Botánico",
    slug: "blanco-botanico",
    price: 275,
    category: { name: "Ramos", slug: "ramos" },
    shortDescription: "Limpio y sereno. Rosas blancas con follaje fino para momentos que piden calma.",
    flowers: ["rosas blancas", "lisianthus", "gypsophila", "follaje"],
    isFeatured: true,
    isAvailable: true,
    order: 3,
  },
  {
    _id: "a4",
    name: "Silvestre Oscuro",
    slug: "silvestre-oscuro",
    price: 340,
    category: { name: "Ramos", slug: "ramos" },
    shortDescription: "Tonos burdeos y vino, con texturas silvestres. Para quienes buscan algo diferente.",
    flowers: ["ranúnculo borgoña", "astilbe", "hojas de roble", "scabiosa"],
    isAvailable: true,
    order: 4,
  },
  {
    _id: "a5",
    name: "Caja Bosque",
    slug: "caja-bosque",
    price: 520,
    category: { name: "Cajas", slug: "cajas" },
    shortDescription: "Arreglo en caja kraft con flores de temporada, musgo y follaje. Huele a bosque.",
    flowers: ["rosas garden", "protea", "musgo", "eucalipto"],
    isFeatured: true,
    isAvailable: true,
    order: 5,
  },
  {
    _id: "a6",
    name: "Detalle Mínimo",
    slug: "detalle-minimo",
    price: 195,
    category: { name: "Cajas", slug: "cajas" },
    shortDescription: "Pequeño, concreto y honesto. Ideal para acompañar un mensaje.",
    flowers: ["mini rosas", "eucalipto", "gypsophila"],
    isAvailable: true,
    order: 6,
  },
  {
    _id: "a7",
    name: "Mesa de Celebración",
    slug: "mesa-de-celebracion",
    price: 920,
    category: { name: "Eventos", slug: "eventos" },
    shortDescription: "Centro de mesa con flores de temporada y elementos naturales. Bodas y eventos.",
    flowers: ["rosas", "peonías", "ramitas de olivo", "velas"],
    isFeatured: true,
    isAvailable: true,
    order: 7,
  },
  {
    _id: "a8",
    name: "Terrario de Suculentas",
    slug: "terrario-de-suculentas",
    price: 175,
    category: { name: "Plantas", slug: "plantas" },
    shortDescription: "Un ecosistema chico. Tres suculentas en recipiente de vidrio con piedra volcánica.",
    flowers: ["suculentas mixtas", "piedra volcánica", "arena"],
    isAvailable: true,
    order: 8,
  },
  {
    _id: "a9",
    name: "Orquídea Negra",
    slug: "orquidea-negra",
    price: 480,
    category: { name: "Plantas", slug: "plantas" },
    shortDescription: "Phalaenopsis en maceta artesanal. Duradera, elegante, sin pretensiones.",
    flowers: ["orquídea phalaenopsis"],
    isAvailable: true,
    order: 9,
  },
];
